name: Falcon CI

# on: [ pull_request, push ]
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies

    - run: pip install -r requirements.txt

    - name: Docker Build and run
      run: |
        docker build . -t muzakkirsaifi/falcon-look-app
        docker run -dit -p 8000:8000 muzakkirsaifi/falcon-look-app

    - name: Test Code
      run: coverage run -m pytest tests/

    - name: Generate the report
      if: ${{ always() }}
      run: coverage report > coverage-report

    - name: Scan image
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: "muzakkirsaifi/falcon-look-app"
        fail-build: true
        severity-cutoff: critical

    

    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: vuln-report
        path: results.sarif

    - name: upload report
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: coverage-report
        path: coverage-report

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: muzakkirsaifi/falcon-look-app:latest


    - name: Create issue on failure
      if: ${{ failure() }}
      run: |
        gh issue create --title "Failure on workflow: ${{ github.workflow }} - ${{ github.sha }}" --body "Failure on Job: ${{ github.job }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}